using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace WindowMetrics.Models
{
    public class Client
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ClientId { get; set; } // Autogenerated client ID
        public string ClientName { get; set; }
        public string CreatedBy { get; set; } = "Spatel";
        public DateTime CreatedWhen { get; set; } = DateTime.Now;
        public string TouchedBy { get; set; } = "Spatel";
        public DateTime TouchedWhen { get; set; } = DateTime.Now;
    }
}
